### ISSUE TITLE
Changement de thème : reborn porc flavor

### ISSUE THREAD

**Issue by skelz0r** [blackbirdco/tech_blog#4]
Une liste: https://github.com/imathis/octopress/wiki/3rd-Party-Octopress-Themes

Des sympas: 
1. https://github.com/sevenadrian/MediumFox
2. http://github.com/alexgaribay/octoflat
3. http://vladigleba.com/ (celui que je voulais avoir pour mon propre blog a l'époque)
4. https://tommy351.github.io/Octopress-Theme-Slash/
5. https://github.com/lucaslew/whitespace
6. https://github.com/mjhea0/whiterspace
7. https://github.com/lmm/SmallFox
8. https://github.com/mjhea0/noLogo#screenshots

**Comment by zaratan** [comment]
https://github.com/shashankmehta/greyshade

**Comment by skelz0r** [comment]
zar et moi http://rfvallina.com/blog/2015/11/22/verify-shopify-webhooks-using-node-dot-js/

**Comment by sal-himd** [comment]
J'aime aussi.
